databases:
  - name: rctv
    plan: starter
    region: ohio
services:
  - type: web
    plan: starter
    numInstances: 1
    name: rctv
    env: python
    region: ohio
    buildCommand: "./bin/build.sh"
    startCommand: 'gunicorn --access-logformat ''%(h)s %(l)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" reqtime: %(M)s ms'' rctv.wsgi:application'
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rctv
          property: connectionString
      - fromGroup: rctv-prod-env
